# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "greeter.CounterReply" do
    optional :counter, :int64, 1
  end
  add_message "greeter.Empty" do
  end
end

module Greeter
  CounterReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.CounterReply").msgclass
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.Empty").msgclass
end
