// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package greeter is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	CounterReply
	Empty
*/
package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CounterReply struct {
	Counter int64 `protobuf:"varint,1,opt,name=counter" json:"counter,omitempty"`
}

func (m *CounterReply) Reset()                    { *m = CounterReply{} }
func (m *CounterReply) String() string            { return proto.CompactTextString(m) }
func (*CounterReply) ProtoMessage()               {}
func (*CounterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CounterReply) GetCounter() int64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*CounterReply)(nil), "greeter.CounterReply")
	proto.RegisterType((*Empty)(nil), "greeter.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	GetCounter(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CounterReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetCounter(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CounterReply, error) {
	out := new(CounterReply)
	err := grpc.Invoke(ctx, "/greeter.Greeter/GetCounter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	GetCounter(context.Context, *Empty) (*CounterReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greeter.Greeter/GetCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetCounter(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greeter.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCounter",
			Handler:    _Greeter_GetCounter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2f, 0x4a, 0x4d, 0x2d,
	0x49, 0x2d, 0x52, 0xd2, 0xe0, 0xe2, 0x71, 0xce, 0x2f, 0xcd, 0x2b, 0x49, 0x2d, 0x0a, 0x4a, 0x2d,
	0xc8, 0xa9, 0x14, 0x92, 0xe0, 0x62, 0x4f, 0x86, 0xf0, 0x25, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83,
	0x60, 0x5c, 0x25, 0x76, 0x2e, 0x56, 0xd7, 0xdc, 0x82, 0x92, 0x4a, 0x23, 0x07, 0x2e, 0x76, 0x77,
	0x88, 0x6e, 0x21, 0x53, 0x2e, 0x2e, 0xf7, 0xd4, 0x12, 0xa8, 0x01, 0x42, 0x7c, 0x7a, 0x50, 0x53,
	0xf5, 0xc0, 0x0a, 0xa5, 0x44, 0xe1, 0x7c, 0x64, 0x2b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x8e, 0x30,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x52, 0x39, 0x3f, 0x05, 0x95, 0x00, 0x00, 0x00,
}
